In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# **DataSet Loading...**



In [2]:
# importing pandas module 
import os
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np

  
# reading csv file 
data = pd.read_csv("/content/drive/My Drive/Minor/shuffled_dataset.csv") 
#data= data.fillna(0)


In [3]:
X=np.array(data.iloc[:,3:32403])
Y=data.iloc[:,2].values
print(Y)
print(X)

[2 1 0 ... 2 2 2]
[[253 253 253 ... 247 246 246]
 [254 254 254 ... 253 253 254]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [253 253 253 ... 250 250 250]
 [  0   0   0 ...   0   0   0]]


In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3 ,random_state=42)

# **Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=1500, random_state=42)
regressor.fit(X, Y)

import pickle

with open('/content/drive/My Drive/Minor/model.pck', 'wb') as f:
    pickle.dump(regressor,f)



# **SVC**

In [5]:
from sklearn.svm import SVC # "Support Vector Classifier" 
clf = SVC(gamma='auto') 
clf.fit(X, Y)
# y_pred=clf.predict(X_test)
import pickle

with open('/content/drive/My Drive/Minor/model_SVC.pck', 'wb') as f:
    pickle.dump(clf, f)
  
# from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# print(confusion_matrix(y_test,y_pred))
# print(classification_report(y_test,y_pred))
# sv=accuracy_score(y_test, y_pred)
# print(sv)

In [7]:
y_pred = clf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
kn=accuracy_score(y_test, y_pred) *100
print(kn)

[[349   0   0]
 [  2 357   0]
 [  0   0 373]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       349
           1       1.00      0.99      1.00       359
           2       1.00      1.00      1.00       373

    accuracy                           1.00      1081
   macro avg       1.00      1.00      1.00      1081
weighted avg       1.00      1.00      1.00      1081

99.81498612395929


# **Stacking(SVC+RF)**

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC # "Support Vector Classifier"
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
estimators = [
     ('rf', RandomForestClassifier(n_estimators=1000, random_state=42)),
     ('svr',SVC(gamma='auto') )
     ]
svcrf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
svcrf.fit(X,Y)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


StackingClassifier(cv=None,
                   estimators=[('rf',
                                RandomForestClassifier(bootstrap=True,
                                                       ccp_alpha=0.0,
                                                       class_weight=None,
                                                       criterion='gini',
                                                       max_depth=None,
                                                       max_features='auto',
                                                       max_leaf_nodes=None,
                                                       max_samples=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                     

In [9]:
y_pred = svcrf.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
accuracy_score(y_test, y_pred) *100

[[349   0   0]
 [  2 357   0]
 [  0   0 373]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       349
           1       1.00      0.99      1.00       359
           2       1.00      1.00      1.00       373

    accuracy                           1.00      1081
   macro avg       1.00      1.00      1.00      1081
weighted avg       1.00      1.00      1.00      1081



99.81498612395929

In [17]:
import pickle

with open('/content/drive/My Drive/Minor/stackclassifier.pck', 'wb') as f:
    pickle.dump(svcrf,f)


# **Stacking(KNN+RF)**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import RandomForestClassifier

estimators = [
     ('knn',  KNeighborsClassifier(n_neighbors=2)),
     ('rf', RandomForestClassifier(n_estimators=1000, random_state=42))
     ]
knnrf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
knnrf.fit(X_train, y_train)
y_pred = knnrf.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
accuracy_score(y_test, y_pred) *100


In [ ]:
import pickle

with open('/content/drive/My Drive/Minor/knnrf.pck', 'wb') as f:
    pickle.dump(knnrf,f)

# **Stacking(RF)**

In [10]:
!pip3 install xgboost

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
import xgboost as xgb

estimators = [
     ('rf', RandomForestClassifier(n_estimators=1000, random_state=42))
     ]
xgr = StackingClassifier(estimators=estimators, final_estimator=xgb.XGBClassifier())
xgr.fit(X,Y)
xgr.score(X_test,y_test)


0.9972247918593895

In [19]:
import pickle

with open('/content/drive/My Drive/Minor/xgrf.pck', 'wb') as f:
    pickle.dump(xgr,f)