In [0]:
!pip install ipython-autotime

%load_ext autotime

  Created wheel for ipython-autotime: filename=ipython_autotime-0.1-cp36-none-any.whl size=1832 sha256=86f7df2eb79a29e8d21e669a6c57e37e643ea2471ad9b8f2a408304c291230c8
  Stored in directory: /root/.cache/pip/wheels/d2/df/81/2db1e54bc91002cec40334629bc39cfa86dff540b304ebcd6e
Successfully built ipython-autotime


In [0]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd 

time: 2.19 ms


In [0]:
data = pd.read_csv("/content/drive/My Drive/Minor2/shuffled_dataset.csv") 
data.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 1    0  ...  0.1103  0.1104  0.1105  0.1106
0         424           424           2  253  ...     248     247     246     246
1        1927          1927           1  254  ...     253     253     253     254
2        2740          2740           0    0  ...       0       0       0       0
3         404           404           2  255  ...     254     254     254     254
4        1280          1280           2  249  ...     250     250     249     250

[5 rows x 32403 columns]

time: 1min 31s


In [0]:
import numpy as np
X=np.array(data.iloc[:,3:32403].values)
Y=data.iloc[:,2].values
print(Y)
print(X)

[2 1 0 ... 2 2 2]
[[253 253 253 ... 247 246 246]
 [254 254 254 ... 253 253 254]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [253 253 253 ... 250 250 250]
 [  0   0   0 ...   0   0   0]]
time: 620 ms


In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

time: 1.83 s


In [0]:
from sklearn.tree import DecisionTreeClassifier
classifier = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=3),
    n_estimators=100
)
decisada = classifier.fit(X_train, Y_train)

time: 22min 17s


In [0]:
predictions = classifier.predict(X_test)

time: 5.91 s


In [0]:
print("Accuracy:",metrics.accuracy_score(Y_test, predictions))

Accuracy: 0.7725381414701803
time: 1.93 ms


In [0]:
import pickle

with open('/content/drive/My Drive/Minor2/decisionada.pck', 'wb') as f:
    pickle.dump(decisada,f)

time: 24 ms
