In [0]:
!pip install ipython-autotime

%load_ext autotime

  Created wheel for ipython-autotime: filename=ipython_autotime-0.1-cp36-none-any.whl size=1832 sha256=80c12d5f5cad5ffce86b5a2b60df4da06386f3dd2aa925d74552d92ebd477d30
  Stored in directory: /root/.cache/pip/wheels/d2/df/81/2db1e54bc91002cec40334629bc39cfa86dff540b304ebcd6e
Successfully built ipython-autotime


In [0]:
pip install xgboost

In [0]:
import os
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import xgboost as xgb

time: 2.53 ms


In [0]:
data = pd.read_csv("/content/drive/My Drive/Minor2/shuffled_dataset.csv") 
data= data.fillna(0)
data.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 1    0  ...  0.1103  0.1104  0.1105  0.1106
0         424           424           2  253  ...     248     247     246     246
1        1927          1927           1  254  ...     253     253     253     254
2        2740          2740           0    0  ...       0       0       0       0
3         404           404           2  255  ...     254     254     254     254
4        1280          1280           2  249  ...     250     250     249     250

[5 rows x 32403 columns]

time: 1min 31s


In [0]:
data.tail()

Unnamed: 0  Unnamed: 0.1  Unnamed: 1    0  ...  0.1103  0.1104  0.1105  0.1106
3596        1239          1239           2  251  ...     246     246     246     246
3597         524           524           2  253  ...     254     254     254     254
3598         828           828           2    0  ...       0       0       0       0
3599         306           306           2  253  ...     250     250     250     250
3600         284           284           2    0  ...       0       0       0       0

[5 rows x 32403 columns]

time: 110 ms


In [0]:
X=np.array(data.iloc[:,3:32403].values)
Y=data.iloc[:,2].values
print(Y)
print(X)

[2 1 0 ... 2 2 2]
[[253 253 253 ... 247 246 246]
 [254 254 254 ... 253 253 254]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [253 253 253 ... 250 250 250]
 [  0   0   0 ...   0   0   0]]
time: 311 ms


In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

time: 6.04 s


In [0]:
D_train = xgb.DMatrix(X_train, label=Y_train)
D_test = xgb.DMatrix(X_test, label=Y_test)

time: 1.07 s


In [0]:
param = {
    'eta': 0.1, 
    'max_depth': 5,  
    'objective': 'multi:softprob',  
    'num_class': 3,
    } 

steps = 200  # The number of training iterations

time: 1.69 ms


In [0]:
model = xgb.train(param, D_train, steps)

time: 27min 31s


In [0]:
from sklearn.metrics import precision_score, recall_score, accuracy_score

preds = model.predict(D_test)
best_preds = np.asarray([np.argmax(line) for line in preds])

print("Precision = {}".format(precision_score(Y_test, best_preds, average='macro')))
print("Recall = {}".format(recall_score(Y_test, best_preds, average='macro')))
print("Accuracy = {}".format(accuracy_score(Y_test, best_preds)))

Precision = 0.9435208158520944
Recall = 0.944629285011623
Accuracy = 0.9431345353675451
time: 217 ms


In [0]:
import pickle

with open('/content/drive/My Drive/Minor2/xgboost.pck', 'wb') as f:
    pickle.dump(model,f)

time: 30.2 ms
